name = "notion-mcp-community"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[[routes]]
pattern = "notion-mcp-community.node2flow.net"
custom_domain = true

[observability]
enabled = true
